esphome:
  name: esphome-web-037698
  friendly_name: ESP32-C3 1
  min_version: 2025.9.0
  name_add_mac_suffix: false

esp32:
  variant: esp32c3
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

sensor:
  - platform: dht
    pin: GPIO21
    temperature:
      name: "Temperature"
      accuracy_decimals: 0

    humidity:
      name: "Humidity"
    update_interval: 10s

switch:
  - platform: gpio
    pin: GPIO5
    name: "Button"
    id: led_switch

  - platform: template
    name: "Tapo P110 Mirror"
    id: tapo_mirror
    lambda: |-
      // Read actual Tapo state from Home Assistant
      if (id(tapo_real).state) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - homeassistant.service:
          service: switch.turn_on
          data:
            entity_id: switch.salon_tv_yani
    turn_off_action:
      - homeassistant.service:
          service: switch.turn_off
          data:
            entity_id: switch.salon_tv_yani

  - platform: homeassistant
    entity_id: switch.salon_tv_yani
    id: tapo_real

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO3
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Tapo Button"
    entity_category: "diagnostic"
    filters:
      - delayed_on: 10ms
    on_press:
      - switch.toggle: tapo_mirror
